// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xliqdqaerqaezbnppzdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsaXFkcWFlcnFhZXpibnBwemRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTc3MjAsImV4cCI6MjA2MjczMzcyMH0.1I02V2oeB-kn4p-YzFHjzTsYJaU3ul_eEP3Phzb1F9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);